#!/bin/bash
# REV03: Mon Feb 12 12:55:26 WIB 2018
# START: Mon Sep  4 16:42:56 WIB 2017

# R: Does ".thisfile.txt" exists? Run "bash a04-does-it-exist"

# Copyright (C)2017-2018 Rahmat M. Samik-Ibrahim
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

FILE=".thisfile.txt"

[ -f $FILE ] && {
  echo "$FILE EXISTS!"
}
[ -f $FILE ] || {
  echo "$FILE does not EXISTS!"
}

exit

