#!/bin/bash
# REV04: Mon Feb 12 12:56:40 WIB 2018
# START: Mon Sep  5 14:25:10 WIB 2016

# R: Finding "EXISTS". Just run "bash a05-finding-EXIST"

# Copyright (C) 2016-2018 http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


echo "File list:"
echo "=========="

for file in `ls a[01]*`
do
   echo -n $file
   if grep -q EXIST $file
      then
      echo -n " YES *******"
   fi
   echo ""
	
done

exit 0
