#!/bin/bash
# REV04: Mon Feb 12 13:00:56 WIB 2018
# START: Mon Sep  5 14:34:41 WIB 2016

# R: Just run "bash a07-loop"

# Copyright (C) 2016-2018 http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

echo "============="
echo 'Loop with [*]'
for ii in "$*"
do
   echo $ii
done

echo "=============="
echo 'Loop with [@]'
for ii in "$@"
do
   echo $ii
done
exit 0

